# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68584b019e0df302bcb5d40a430440fa0ed114d7d14c666183ebc05ecacb1ceeabe28a23d1fcaaea5235cee2c5e795488c65aa45d7591a67e1343ac508653330

test:
  secret_key_base: c5e9af53ade4fe527004623219dde69f186225e0366b640f033ccaf5dbf3123d41bef4697de540fe67a65250428202e9e525f7c26da818f8c4768a8282d71423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
